<?php
defined( 'ABSPATH' ) || exit;

/**
 * PawaPay API Client (Merchant API v1).
 */
class WC_PawaPay_API {

    const SANDBOX_URL    = 'https://api.sandbox.pawapay.io';
    const PRODUCTION_URL = 'https://api.pawapay.io';

    private string $api_token;
    private string $base_url;
    private bool   $debug;

    public function __construct( string $api_token, bool $sandbox = false, bool $debug = false ) {
        $this->api_token = $api_token;
        $this->base_url  = $sandbox ? self::SANDBOX_URL : self::PRODUCTION_URL;
        $this->debug     = $debug;
    }

    /**
     * PawaPay v1 statementDescription: 4–22 alphanumeric characters and spaces.
     */
    public static function sanitize_statement_description( string $description ): string {
        $clean = preg_replace( '/[^a-zA-Z0-9 ]/', ' ', $description ) ?? '';
        $clean = trim( (string) preg_replace( '/\s+/', ' ', $clean ) );

        if ( strlen( $clean ) < 4 ) {
            $clean = 'Order payment';
        }

        return substr( $clean, 0, 22 );
    }

    /**
     * Initiate a deposit (customer pays).
     *
     * @param string $deposit_id  Unique UUID v4 generated by us
     * @param string $amount      e.g. "10.00"
     * @param string $currency    e.g. "USD", "CDF"
     * @param string $mno         Provider code e.g. "ORANGE_COD"
     * @param string $msisdn      International phone, no +
     * @param string $description Statement description (sanitized to 4–22 [A-Za-z0-9 ])
     * @param array  $metadata    Optional key-value pairs (max 10)
     */
    public function initiate_deposit(
        string $deposit_id,
        string $amount,
        string $currency,
        string $mno,
        string $msisdn,
        string $description = 'Order payment',
        array  $metadata = []
    ): array {
        $payload = [
            'depositId'            => $deposit_id,
            'amount'               => $amount,
            'currency'             => $currency,
            'correspondent'        => $mno,
            'payer'                => [
                'type'    => 'MSISDN',
                'address' => [ 'value' => $msisdn ],
            ],
            'customerTimestamp'    => gmdate( 'Y-m-d\TH:i:s\Z' ),
            'statementDescription' => self::sanitize_statement_description( $description ),
        ];

        if ( ! empty( $metadata ) ) {
            $meta_array = [];
            foreach ( array_slice( $metadata, 0, 10 ) as $key => $value ) {
                $meta_array[] = [ 'fieldName' => (string) $key, 'fieldValue' => (string) $value ];
            }
            $payload['metadata'] = $meta_array;
        }

        return $this->request( 'POST', '/deposits', $payload );
    }

    public function check_deposit_status( string $deposit_id ): array {
        return $this->request( 'GET', '/deposits/' . $deposit_id );
    }

    public function get_availability(): array {
        return $this->request( 'GET', '/availability' );
    }

    public function get_active_configuration(): array {
        return $this->request( 'GET', '/active-conf' );
    }

    private function request( string $method, string $endpoint, array $body = [] ): array {
        $url  = $this->base_url . $endpoint;
        $args = [
            'method'  => $method,
            'timeout' => 30,
            'headers' => [
                'Authorization' => 'Bearer ' . $this->api_token,
                'Content-Type'  => 'application/json',
                'Accept'        => 'application/json',
            ],
        ];

        if ( $method === 'POST' && ! empty( $body ) ) {
            $args['body'] = wp_json_encode( $body );
        }

        if ( $this->debug ) {
            wc_get_logger()->debug(
                '[PawaPay] → ' . $method . ' ' . $url . ' | Payload: ' . wp_json_encode( $body ),
                [ 'source' => 'wc-pawapay' ]
            );
        }

        $response = wp_remote_request( $url, $args );

        if ( is_wp_error( $response ) ) {
            $this->log( 'WP_Error: ' . $response->get_error_message() );
            return [ 'error' => $response->get_error_message() ];
        }

        $code = wp_remote_retrieve_response_code( $response );
        $raw  = wp_remote_retrieve_body( $response );
        $data = json_decode( $raw, true ) ?? [];

        if ( $this->debug ) {
            wc_get_logger()->debug(
                '[PawaPay] ← HTTP ' . $code . ' | Body: ' . $raw,
                [ 'source' => 'wc-pawapay' ]
            );
        }

        $data['_http_code'] = $code;
        return $data;
    }

    private function log( string $message ): void {
        wc_get_logger()->error( '[PawaPay] ' . $message, [ 'source' => 'wc-pawapay' ] );
    }

    public static function generate_uuid(): string {
        return sprintf(
            '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
            mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ),
            mt_rand( 0, 0xffff ),
            mt_rand( 0, 0x0fff ) | 0x4000,
            mt_rand( 0, 0x3fff ) | 0x8000,
            mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff )
        );
    }
}
